apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bike-lgbm"
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa
    ### START CONF HERE
    canaryTrafficPercent: 30
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/6/370e8de14a6c4491b05d4b020dd2cb8b/artifacts/lgbm-bike"
    ### END CONF HERE
